let roles = [
  {
    name: "customer-insert",
    module: "Exchange",
    title: "Customer Form",
    index: 2,
  },
  {
    name: "customer-update",
    module: "Exchange",
    title: "Customer Form",
    index: 2,
  },
  {
    name: "customer-remove",
    module: "Exchange",
    title: "Customer Form",
    index: 2,
  },
  {
    name: "exchange-rate-insert",
    module: "Exchange",
    moduleRole: "exchangeModule",
    title: "Customer Form",
    index: 2,
  },
  {
    name: "exchange-rate-update",
    module: "Exchange",
    moduleRole: "exchangeModule",
    title: "Customer Form",
    index: 2,
  },
  {
    name: "exchange-rate-remove",
    module: "Exchange",
    moduleRole: "exchangeModule",
    title: "Customer Form",
    index: 2,
  },
  {
    name: "transaction-cash-deposit-insert",
    module: "Exchange",
    moduleRole: "exchangeModule",
    title: "Customer Form",
    index: 2,
  },
  {
    name: "transaction-cash-deposit-update",
    module: "Exchange",
    moduleRole: "exchangeModule",
    title: "Customer Form",
    index: 2,
  },
  {
    name: "transaction-cash-deposit-remove",
    module: "Exchange",
    moduleRole: "exchangeModule",
    title: "Customer Form",
    index: 2,
  },
  {
    name: "transaction-transfer-insert",
    module: "Exchange",
    moduleRole: "exchangeModule",
    title: "Customer Form",
    index: 2,
  },
  {
    name: "transaction-transfer-update",
    module: "Exchange",
    moduleRole: "exchangeModule",
    title: "Customer Form",
    index: 2,
  },
  {
    name: "transaction-transfer-remove",
    module: "Exchange",
    moduleRole: "exchangeModule",
    title: "Customer Form",
    index: 2,
  },
  {
    name: "transaction-exchange-insert",
    module: "Exchange",
    moduleRole: "exchangeModule",
    title: "Customer Form",
    index: 2,
  },
  {
    name: "transaction-exchange-update",
    module: "Exchange",
    moduleRole: "exchangeModule",
    title: "Customer Form",
    index: 2,
  },
  {
    name: "transaction-exchange-remove",
    module: "Exchange",
    moduleRole: "exchangeModule",
    title: "Customer Form",
    index: 2,
  },
  {
    name: "money-transfer-insert",
    module: "Exchange",
    moduleRole: "exchangeModule",
    title: "Customer Form",
    index: 2,
  },
  {
    name: "money-transfer-update",
    module: "Exchange",
    moduleRole: "exchangeModule",
    title: "Customer Form",
    index: 2,
  },
  {
    name: "money-transfer-remove",
    module: "Exchange",
    moduleRole: "exchangeModule",
    title: "Customer Form",
    index: 2,
  },

  // report
];
export default roles;